// Golden tests for the NanoDet-Plus field-detector decode (cpp/detect).
//
// Ground truth is generated by model-training/nanodet/gen_golden (planted,
// well-separated detections so NMS ordering is unambiguous across impls) and
// stored under cpp/tests/fixtures/nanodet_golden/. NANODET_FIXTURE_DIR is set
// by CMake to that absolute path.
#include <cstdint>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "detect/nanodet_decode.hpp"
#include "gtest/gtest.h"

namespace {

std::string fixture(const std::string& name) {
    return std::string(NANODET_FIXTURE_DIR) + "/" + name;
}

std::vector<float> read_floats(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    EXPECT_TRUE(f.good()) << "missing fixture: " << path;
    std::vector<float> v;
    float x;
    while (f.read(reinterpret_cast<char*>(&x), sizeof(float))) v.push_back(x);
    return v;
}

struct ExpDet {
    int cls;
    float score;
    float x1, y1, x2, y2;
};

std::vector<ExpDet> read_expected(const std::string& path) {
    std::ifstream f(path);
    EXPECT_TRUE(f.good()) << "missing fixture: " << path;
    std::vector<ExpDet> out;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty()) continue;
        std::istringstream ss(line);
        ExpDet d;
        ss >> d.cls >> d.score >> d.x1 >> d.y1 >> d.x2 >> d.y2;
        out.push_back(d);
    }
    return out;
}

constexpr int kChannelWidth = 62;  // 30 classes + 4*(7+1)

}  // namespace

// Center priors must match NanoDet's get_single_level_center_priors exactly
// (cx=col*stride, cy=row*stride, levels concatenated in stride order).
TEST(NanoDetDecode, CenterPriorsMatchGolden) {
    auto priors = dlscan::detect::generate_center_priors(416, {8, 16, 32, 64});
    auto golden = read_floats(fixture("center_priors.bin"));  // [A*3]
    ASSERT_EQ(golden.size(), priors.size() * 3);
    for (size_t a = 0; a < priors.size(); ++a) {
        EXPECT_FLOAT_EQ(priors[a].cx, golden[a * 3 + 0]) << "anchor " << a;
        EXPECT_FLOAT_EQ(priors[a].cy, golden[a * 3 + 1]) << "anchor " << a;
        EXPECT_FLOAT_EQ(priors[a].stride, golden[a * 3 + 2]) << "anchor " << a;
    }
}

namespace {
void check_fixture(int n) {
    auto raw = read_floats(fixture("raw_" + std::to_string(n) + ".bin"));
    ASSERT_EQ(raw.size() % kChannelWidth, 0u);
    const size_t num_anchors = raw.size() / kChannelWidth;

    dlscan::detect::NanoDetConfig cfg;  // 416, {8,16,32,64}, 30, reg_max 7,
                                        // score_thr 0.05, nms_iou 0.6, max 100
    auto got = dlscan::detect::nanodet_decode(raw.data(), num_anchors, cfg);
    auto exp = read_expected(fixture("expected_" + std::to_string(n) + ".txt"));

    ASSERT_EQ(got.size(), exp.size()) << "detection count mismatch, fixture " << n;
    for (size_t i = 0; i < exp.size(); ++i) {
        EXPECT_EQ(got[i].class_id, exp[i].cls) << "fixture " << n << " det " << i;
        EXPECT_NEAR(got[i].confidence, exp[i].score, 1e-4f) << "fixture " << n << " det " << i;
        EXPECT_NEAR(got[i].x1, exp[i].x1, 0.05f) << "fixture " << n << " det " << i;
        EXPECT_NEAR(got[i].y1, exp[i].y1, 0.05f) << "fixture " << n << " det " << i;
        EXPECT_NEAR(got[i].x2, exp[i].x2, 0.05f) << "fixture " << n << " det " << i;
        EXPECT_NEAR(got[i].y2, exp[i].y2, 0.05f) << "fixture " << n << " det " << i;
    }
}
}  // namespace

TEST(NanoDetDecode, MatchesGoldenFixture0) { check_fixture(0); }
TEST(NanoDetDecode, MatchesGoldenFixture1) { check_fixture(1); }
